# ─────────────────────────────────────────────────────────────────────────────
# CaféSmart — multi-stage production Docker image
# ─────────────────────────────────────────────────────────────────────────────
# Stage 1: install Next.js deps with full toolchain
# Stage 2: build the Next.js standalone bundle
# Stage 3: install Python deps for the ML microservice
# Stage 4: minimal runtime with both Node and Python runtimes
# ─────────────────────────────────────────────────────────────────────────────
#
# All Node base images are pinned to `node:22-alpine` to match the engine
# requirements of recent Prisma 7 + @testing-library/jest-dom 7 packages.
# ─────────────────────────────────────────────────────────────────────────────

# ─── Stage 1: deps ──────────────────────────────────────────────────────────
FROM node:22-alpine AS deps
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app

# Copy the manifest files first so this layer caches well.
COPY package.json package-lock.json* ./

# Copy the Prisma schema and config BEFORE `npm ci` so the
# `postinstall` script (`prisma generate`) can find the schema.
# Without this, npm ci fails with:
#   "Could not find Prisma Schema that is required for this command."
COPY prisma ./prisma
COPY prisma.config.ts ./

# `--include=dev` so the postinstall script and devDeps are installed
# (Prisma 7 ships a TypeScript-based client that needs the CLI to generate).
RUN npm ci --include=dev

# ─── Stage 2: build ─────────────────────────────────────────────────────────
FROM node:22-alpine AS builder
RUN apk add --no-cache libc6-compat openssl
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Prisma client is already generated by the postinstall hook in `deps`,
# but re-run for safety in case the schema changed.
RUN npx prisma generate

ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ─── Stage 3: ML service deps ──────────────────────────────────────────────
# Build Python wheels for the ML microservice in a dedicated Alpine stage.
# We can't do this in the runner because:
#
#   1. The runner image is Alpine (musl libc), and pip cannot fetch
#      manylinux wheels built for glibc — so scikit-learn must be
#      built from sdist, which needs a compiler toolchain.
#
#   2. The ml-deps stage runs the SAME ``node:22-alpine`` base and
#      installs the SAME ``apk add python3 py3-pip`` as the runner,
#      so the Python interpreter and site-packages layout match exactly.
#
# We build wheels once here into ``/wheels``, then install them into
# the runtime image without needing the compiler there.
FROM node:22-alpine AS ml-deps
RUN apk add --no-cache python3 python3-dev py3-pip \
      gcc musl-dev linux-headers g++ make \
      fortify-headers libffi-dev openssl-dev
WORKDIR /ml
COPY ml-service/requirements.txt ./requirements.txt
RUN pip wheel --no-cache-dir \
        --wheel-dir=/wheels -r requirements.txt
COPY ml-service/ ./

# ─── Stage 4: runtime ──────────────────────────────────────────────────────
FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV ML_SERVICE_PORT=8000

# Install Python + pip for the ML service (slim, but self-contained)
RUN apk add --no-cache python3 py3-pip

# Non-root user for runtime safety
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# Copy Next.js standalone output
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma ./node_modules/.prisma

# Copy ML service
COPY --from=ml-deps --chown=nextjs:nodejs /ml /app/ml-service

# Install pre-built Python wheels for the ML service. The wheels were
# built in the ``ml-deps`` stage against the SAME Alpine/Python
# interpreter, so they are ABI-compatible with the runtime image's
# system Python — no compiler toolchain needed in this layer.
COPY --from=ml-deps /wheels /wheels
RUN pip install --no-cache-dir --break-system-packages \
        --no-index --find-links=/wheels \
        -r /app/ml-service/requirements.txt && \
    rm -rf /wheels /root/.cache/pip

# Copy entrypoint script and make it executable. The entrypoint validates
# required env vars BEFORE starting the app so misconfiguration fails
# fast with a clear message instead of a 500 from Prisma.
#
# Belt-and-suspenders: also run `dos2unix` (or a sed fallback) to strip
# any stray Windows line endings. Without this, a shebang of `#!/bin/sh\r`
# on a CRLF-authored file causes:
#   "exec /usr/local/bin/docker-entrypoint.sh: no such file or directory"
# because the kernel tries to exec `/bin/sh\r`, which doesn't exist.
COPY --chmod=755 docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN if command -v dos2unix >/dev/null 2>&1; then \
      dos2unix /usr/local/bin/docker-entrypoint.sh; \
    else \
      sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh; \
    fi && \
    head -c 10 /usr/local/bin/docker-entrypoint.sh | od -c | head -1

# Create uploads dir if any
RUN mkdir -p /app/uploads && chown -R nextjs:nodejs /app/uploads

USER nextjs

EXPOSE 3000
EXPOSE 8000

# Healthcheck (Node)
HEALTHCHECK --interval=30s --timeout=5s --start-period=20s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://127.0.0.1:3000/api/ml/health || exit 1

# Use the entrypoint to validate env, then launch the Node server.
# `serve` arguments can override the default command if needed.
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["node", "server.js"]

